_BASE_: "base_configs/COCO-Detection/faster_rcnn_R_50_FPN_3x.yaml"
DATASETS:
  TRAIN: ("KDN_train", )
  TEST: ("KDN_val", )
MODEL:
  WEIGHTS: "pretrained/R-50.pkl"
  ROI_HEADS:
    NUM_CLASSES: 3
DATALOADER:
  NUM_WORKERS: 4
SOLVER:
  IMS_PER_BATCH: 32
  BASE_LR: 0.05
  STEPS: (2000, 5000, 10000)
  WARMUP_ITERS: 2000
  MAX_ITER: 20000
  GAMMA: 0.2
  CHECKPOINT_PERIOD: 1
TEST:
  EVAL_PERIOD: 1
